name: Deployment Exercise 1
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Test code
        run: npm run test
      - name: Build project
        run: npm run build
      - name: Deploy code
        run: echo "Deploying code..."

